### PR TITLE
 tests/benches: add 'autojump' benches 

### PR DESCRIPTION
**Pull request by euank**
This is part of #47; adding 'autojump' to the benchmark harness was fairly straightforwards, so this should be easy to review.

I'll redo benchmark results and analysis in a separate PR once I've added the 3rd contestant.

### CODE REVIEW

**Comment by euank** [comment]
If you are curious, here's the output I get running this:

```
$ cargo bench --features=nightly                     

test bench::cd_50_bench_autojump_bash         ... bench:  20,123,148 ns/iter (+/- 8,669,857)
test bench::cd_50_bench_autojump_zsh          ... bench: 946,111,021 ns/iter (+/- 97,186,985)
test bench::cd_50_bench_fasd_bash             ... bench:  20,723,596 ns/iter (+/- 2,576,302)
test bench::cd_50_bench_fasd_zsh              ... bench:  14,490,935 ns/iter (+/- 1,856,615)
test bench::cd_50_bench_nojumper_bash         ... bench:   2,344,456 ns/iter (+/- 152,693)
test bench::cd_50_bench_nojumper_zsh          ... bench:     792,240 ns/iter (+/- 265,761)
test bench::cd_50_bench_pazi_bash             ... bench:   2,514,666 ns/iter (+/- 233,763)
test bench::cd_50_bench_pazi_zsh              ... bench:  68,222,901 ns/iter (+/- 5,314,358)
test bench::cd_bench_autojump_bash            ... bench:  19,010,223 ns/iter (+/- 9,581,671)
test bench::cd_bench_autojump_zsh             ... bench:  20,397,823 ns/iter (+/- 11,318,822)
test bench::cd_bench_fasd_bash                ... bench:  14,973,885 ns/iter (+/- 1,117,883)
test bench::cd_bench_fasd_zsh                 ... bench:  13,513,140 ns/iter (+/- 960,015)
test bench::cd_bench_nojumper_bash            ... bench:      67,285 ns/iter (+/- 9,778)
test bench::cd_bench_nojumper_zsh             ... bench:      30,565 ns/iter (+/- 1,391)
test bench::cd_bench_pazi_bash                ... bench:   1,458,328 ns/iter (+/- 607,629)
test bench::cd_bench_pazi_zsh                 ... bench:   1,395,058 ns/iter (+/- 464,168)
test bench::jump_bench_autojump_bash          ... bench:  60,205,238 ns/iter (+/- 4,100,645)
test bench::jump_bench_autojump_zsh           ... bench:  57,771,351 ns/iter (+/- 6,814,306)
test bench::jump_bench_fasd_bash              ... bench:  31,039,778 ns/iter (+/- 4,853,615)
test bench::jump_bench_fasd_zsh               ... bench:  30,139,344 ns/iter (+/- 7,934,366)
test bench::jump_bench_pazi_bash              ... bench:   1,466,299 ns/iter (+/- 123,913)
test bench::jump_bench_pazi_zsh               ... bench:   2,922,621 ns/iter (+/- 1,086,853)
test bench::jump_large_db_bench_autojump_bash ... bench:  94,654,920 ns/iter (+/- 8,157,645)
test bench::jump_large_db_bench_autojump_zsh  ... bench:  92,356,179 ns/iter (+/- 8,353,749)
test bench::jump_large_db_bench_fasd_bash     ... bench:  34,686,902 ns/iter (+/- 1,393,460)
test bench::jump_large_db_bench_fasd_zsh      ... bench:  34,014,326 ns/iter (+/- 9,554,104)
test bench::jump_large_db_bench_pazi_bash     ... bench:  19,077,094 ns/iter (+/- 1,117,029)
test bench::jump_large_db_bench_pazi_zsh      ... bench:  22,185,553 ns/iter (+/- 567,129)
```

**Comment by euank** [comment]
Given the `add directory` hook in `autojump` is intentionally backgrounded ([see here](https://github.com/wting/autojump/blob/6a529f4f929042a37e7394d8c91ba31b479189a2/bin/autojump.zsh#L36-L42)), it's interesting that it's so slow.

I would naively expect doing that to completely cheat the benchmark unless it has so much cpu usage it slows down the ability of the shell itself to operate?

Maybe I should investigate this more? Let me know if you can think of an idea for why that might happen.

**Comment by LinuxMercedes** [comment]
I think a large part of autojump's poor performance is due to it calling `pwd` in it's `cd_hook`s. I compared the performance of these two scripts in both `zsh` and `bash` and it turns out that using `${PWD}` is about two orders of magnitude faster:


```sh
path=''
for ((i = 0; i < 100000; i++)); do
	path=${PWD}
done
```

```sh
path=''
for ((i = 0; i < 100000; i++)); do
	path=$(pwd)
done
```

&nbsp;         | cmd zsh | var zsh | cmd bash | var bash
-----------------|-------------|------------|---------------|-------------
Run 1 (s)      | 46.349   | 0.243    | 58.013	   | 0.652
Run 2 (s)	     | 44.419   | 0.248    | 61.52	   | 0.646
Run 3 (s)	     | 46.064   | 0.244    | 59.262      | 0.638
Run 4 (s)	     | 43.866   | 0.253    | 57.863      | 0.654
Run 5 (s)	     | 47.937   | 0.246    | 61.71        | 0.657
Average (s) | 45.727   | 0.2468  | 59.6736   | 0.6494
ns/iter	     | 457,270 | 2,468    | 596,736	   | 6,494

**Comment by euank** [comment]
I think I'll add an extra benchmark and have `cd_bench` and `cd_bench_sync` where I explicitly `wait` for all children of the shell each time.

Implementing that will be fun and probably involve doing it with rust+cgroups rather than more shell.

**Pull request merged**
